version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - server

  postgres:
    container_name: G2H-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: ubuntu
      POSTGRES_DB: postgresDB
      # TZ: America/New_York
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data


  server:
    container_name: G2H-server
    # platform: linux/arm64/v8
    build:
      context: .
    image: g2h-server-img
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./volumes/logs
        target: /server/volumes/logs
